/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class ch_section6_autorelease_JNsAutoreleasePool */

#ifndef _Included_ch_section6_autorelease_JNsAutoreleasePool
#define _Included_ch_section6_autorelease_JNsAutoreleasePool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ch_section6_autorelease_JNsAutoreleasePool
 * Method:    initPool
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_section6_autorelease_JNsAutoreleasePool_initPool
  (JNIEnv *, jclass);

/*
 * Class:     ch_section6_autorelease_JNsAutoreleasePool
 * Method:    releasePool
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ch_section6_autorelease_JNsAutoreleasePool_releasePool
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
